[package]
name = "footprint-repair"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "footprint-repair"
path = "src/main.rs"

[dependencies]
nalgebra = { workspace = true }
gdal = { workspace = true }
las = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
rstar = { workspace = true }
