[package]
name = "lod2-common"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["pipeline"]
pipeline = ["dep:spade", "dep:kiddo", "dep:rayon", "dep:clap", "dep:rstar"]

[dependencies]
nalgebra = { workspace = true }
spade = { workspace = true, optional = true }
kiddo = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
rayon = { workspace = true, optional = true }
clap = { workspace = true, optional = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
rstar = { workspace = true, optional = true }
earcutr = { workspace = true }
